<a href="https://colab.research.google.com/github/winnie-u/My-1st-repo/blob/master/Marathon_problem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
#Matrix for 10 people and 20 tracks is generated 
import numpy as np
import random
a = np.random.rand(10,20)
#Matrix for the length of the tracks is being generated
b = np.random.rand(20,1)
print(a)
print(b)

[[0.9749171  0.12884122 0.63418559 0.09622024 0.15302539 0.33464341
  0.52914603 0.24822139 0.75484876 0.82795713 0.26540024 0.44486134
  0.3470902  0.51374585 0.22896391 0.10960771 0.02691914 0.42228927
  0.62999628 0.02298472]
 [0.16281809 0.26602325 0.68632266 0.71878938 0.07820304 0.07787426
  0.87376495 0.31775621 0.43826153 0.89172428 0.19937534 0.5998836
  0.5645484  0.47590323 0.44871785 0.38922891 0.19251502 0.16816239
  0.10514109 0.97959415]
 [0.95878875 0.9755799  0.87161767 0.38968007 0.81074966 0.30888565
  0.09256634 0.59169597 0.85059449 0.10337098 0.05629798 0.98205948
  0.66215125 0.95343271 0.86607291 0.65082162 0.30785923 0.61029371
  0.93904742 0.0710638 ]
 [0.50744535 0.94917128 0.39412277 0.19774594 0.98152491 0.19902903
  0.14907812 0.02322109 0.45491881 0.83608112 0.45536973 0.46456245
  0.51955075 0.20526867 0.69677696 0.6169695  0.34472207 0.348659
  0.59689577 0.29248983]
 [0.20352879 0.44167375 0.78031922 0.44583936 0.68099242 0.30125071
  0.68806854 0.7238

In [29]:
#Who ran for maximum or minimum total distance?
#Distance matrix
c = (a.dot(b))
print(c)
#Maximum distance
print(c.argmax())
#Minimum distance
print(c.argmin())

[[2.14496319]
 [4.64502547]
 [3.81392506]
 [4.6000867 ]
 [3.70799626]
 [4.35059544]
 [4.35316937]
 [4.18206328]
 [5.14088612]
 [4.41942533]]
8
0


In [30]:
#How much did B run in total
c[1]

array([4.64502547])

In [33]:
#How much did C run in track 0,1,2
d = a[2,0:3]*b[0:3]
print(d.sum())

3.476791527751564


In [34]:
#How much did D run in total on track 0, 2 and 3?
e = a[3,[0,2,3]]*b[[0,2,3]]
print(e.sum())

1.410487374573917


In [51]:
#How much did C, D and E run in total on track 0, 2 and 3?
e = a[2:5,[0,2,3]]*b[[0,2,3]]
print(e.sum())

1.9015340774459453


In [45]:
# How many person beat A on track 1?
(a[1,1]<a[:,1]).sum()

7

In [54]:
#How many person beat A in terms of total distance covered on track 0, 1 and 3?
d = a[0:,[0,1,3]] @ b[[0,1,3]]
print((d[0]<d[:,:]).sum())

9


In [56]:
#How much more did A run in comparison to E?
d = c[4] - c[0]
print(d)

[1.56303308]


In [57]:
# What is the average distance covered by players on track 0?
c[:,[0]].mean(axis = 0)

array([4.13581362])

In [59]:
# What is the average distance covered by A on all tracks combined?
c[0].mean()

2.1449631855979203

In [62]:
#What is the average distance ran by each player in total on all tracks combined?
c[:,0:].mean(axis = 1)

array([2.14496319, 4.64502547, 3.81392506, 4.6000867 , 3.70799626,
       4.35059544, 4.35316937, 4.18206328, 5.14088612, 4.41942533])

In [76]:
#Which track was used the most/least?
print((a.sum(axis = 0)).argmax())
print((a.sum(axis = 0)).argmin())

2
5


In [77]:
#Which is the longest track?
b.argmax()

6

In [78]:
#How many laps was covered on track 3 in average by all players?
a[:,3].mean()

0.5658920537595763